import random
a = random.randint(3, 7)
b = random.randint(3, 7)
X = set()
Y = set()
while len(X) < a:
    X.add(random.randint(0, 10))
while len(Y) < b:
    Y.add(random.randint(0, 10))
print("Zbiór X:", X)
print("Zbiór Y:", Y)
print("Czy X zawiera 5:", 5 in X)
print("Czy X jest podzbiorem Y:", X.issubset(Y))
print("Czy Y jest podzbiorem X:", Y.issubset(X))
print("Suma zbiorów:", X | Y)
print("Różnica X - Y:", X - Y)
print("Różnica Y - X:", Y - X)
print("Iloczyn zbiorów:", X & Y)
print("Największy element w X:", max(X))
print("Największy element w Y:", max(Y))
element = X.pop()
Y.add(element)
print("Po przeniesieniu elementu")
print("X:", X)
print("Y:", Y)
Y.update(X)
print("Po skopiowaniu X do Y")
print("Y:", Y)
X.clear()
Y.clear()
print("Po wyczyszczeniu")
print("X:", X)
print("Y:", Y)